# Generated by Django 4.2.4 on 2023-11-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
