# Generated by Django 4.2.4 on 2023-11-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
