# Generated by Django 4.2.4 on 2023-11-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_historialmovimientos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='costo_prestamo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
