# Generated by Django 4.2.4 on 2023-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_prestamo_dias_retraso_alter_prestamo_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(default='Prestado', max_length=100),
        ),
    ]
