# Generated by Django 4.2.4 on 2023-11-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimientos',
            name='tabla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
